apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-asg
spec:
  selector:
    matchLabels:
      run: nginx
  replicas: 5
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-default
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 500m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 512Mi