--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: xap-test
  region: ap-southeast-2

nodeGroups:
  - name: ng-a-public
    instanceType: t3.micro
    desiredCapacity: 2
  
managedNodeGroups:
  - name: ng-b
    instanceType: t3.micro
    minSize: 1
    maxSize: 3
    desiredCapacity: 2  